name: "Custom Zigbee Gateway"
version: "1.0.0"
slug: "custom_zigbee"
description: "自訂 Zigbee 控制 Add-on (Node.js)"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
init: false
udev: true
privileged: true
ports:
  1883/tcp: 1883
options:
  mqtt_host: "mqtt.server.local"
  mqtt_port: 1883
  mqtt_user: "mqttuser"
  mqtt_pass: "mqttpass"
  zigbee_port: "/dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_48fcb022c649ef118ac8d18cff00cc63-if00-port0"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str
  zigbee_port: str
auto_update: true
image: "ghcr.io/chaoen/bananas-zigbee-addons-{arch}"
