name: "Custom Zigbee Gateway"
version: "1.0.0"
slug: "custom_zigbee"
description: "自訂 Zigbee 控制 Add-on (Node.js)"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
init: false
uart: true
udev: true
services:
  - mqtt:need
hassio_api: true
hassio_role: admin
homeassistant_api: true
ports:
  1883/tcp: 1883
privileged: true
map:
  - type: share
    read_only: false
  - type: homeassistant_config
    read_only: false
    path: /config
  - type: addon_config
    read_only: false
    path: /addon_config
options:
  mqtt_host: "mqtt.server.local"
  mqtt_port: 1883
  mqtt_user: "mqttuser"
  mqtt_pass: "mqttpass"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str
  zigbee_port: str
auto_update: true
image: "ghcr.io/chaoen/bananas-zigbee-addons-{arch}"
