name: "Custom Zigbee Gateway"
version: "1.0.0"
slug: "custom_zigbee"
description: "自訂 Zigbee 控制 Add-on (Node.js)"
arch:
  - aarch64
startup: services
boot: auto
init: false
ports:
  1883/tcp: 1883
devices:
  - /dev/serial/by-id:/dev/serial/by-id
  - /dev/ttyUSB0
  - /dev/ttyACM0
privileged: true
options:
  mqtt_host: "192.168.68.68"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  zigbee_port: "auto"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str
  zigbee_port: str
auto_update: true
image: "ghcr.io/bananas-platform/zigbee-platform/zigbee-addon"
