name: Build and Publish Docker Images

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./custom-zigbee
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/chaoen/bananas-zigbee-addons-amd64:latest
            ghcr.io/chaoen/bananas-zigbee-addons-amd64:${{ github.sha }}
