name: Build and Push Add-on

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker buildx build             --platform linux/amd64,linux/arm64,linux/arm/v7             --push             -t ghcr.io/${{ github.repository_owner }}/zigbee-addon:latest             -t ghcr.io/${{ github.repository_owner }}/zigbee-addon:$(date +%s) .
